// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-NYD9JgPaJlDonH9lZMVLmxz8Laao_I',
    appId: '1:592990957612:web:0d87c0954df69c708a6189',
    messagingSenderId: '592990957612',
    projectId: 'sttresssense',
    authDomain: 'sttresssense.firebaseapp.com',
    storageBucket: 'sttresssense.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kjcrYKFMFnksMq1vtHwM9ikO5F9wFU8',
    appId: '1:592990957612:android:f1db7bd290e9327e8a6189',
    messagingSenderId: '592990957612',
    projectId: 'sttresssense',
    storageBucket: 'sttresssense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACJHE4lQ10MKn9YLUxvKHuqAHP7yzshQc',
    appId: '1:592990957612:ios:17e69ef4b64ccb418a6189',
    messagingSenderId: '592990957612',
    projectId: 'sttresssense',
    storageBucket: 'sttresssense.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.flutterPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACJHE4lQ10MKn9YLUxvKHuqAHP7yzshQc',
    appId: '1:592990957612:ios:17e69ef4b64ccb418a6189',
    messagingSenderId: '592990957612',
    projectId: 'sttresssense',
    storageBucket: 'sttresssense.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.flutterPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY-NYD9JgPaJlDonH9lZMVLmxz8Laao_I',
    appId: '1:592990957612:web:0e08ec7c75da27498a6189',
    messagingSenderId: '592990957612',
    projectId: 'sttresssense',
    authDomain: 'sttresssense.firebaseapp.com',
    storageBucket: 'sttresssense.firebasestorage.app',
  );
}
