// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbghFltIWqrp5NpG1QdfMTeiwNzgkFDU',
    appId: '1:661972026334:web:0a0becc3ee89b1bd58134f',
    messagingSenderId: '661972026334',
    projectId: 'gp-2-fe52b',
    authDomain: 'gp-2-fe52b.firebaseapp.com',
    storageBucket: 'gp-2-fe52b.firebasestorage.app',
    measurementId: 'G-B6EXRY7ZX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDU_EvuipS_qx8uM9qgXWN3NmtCxTpLZA',
    appId: '1:661972026334:android:f02af1aaf7e346b358134f',
    messagingSenderId: '661972026334',
    projectId: 'gp-2-fe52b',
    storageBucket: 'gp-2-fe52b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMY8KBVG_Zq5xDOZFLv3oU1k7iU4LS74',
    appId: '1:661972026334:ios:2c5dc94ef8bf242e58134f',
    messagingSenderId: '661972026334',
    projectId: 'gp-2-fe52b',
    storageBucket: 'gp-2-fe52b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMY8KBVG_Zq5xDOZFLv3oU1k7iU4LS74',
    appId: '1:661972026334:ios:2c5dc94ef8bf242e58134f',
    messagingSenderId: '661972026334',
    projectId: 'gp-2-fe52b',
    storageBucket: 'gp-2-fe52b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASbghFltIWqrp5NpG1QdfMTeiwNzgkFDU',
    appId: '1:661972026334:web:5397d0aeb722c9be58134f',
    messagingSenderId: '661972026334',
    projectId: 'gp-2-fe52b',
    authDomain: 'gp-2-fe52b.firebaseapp.com',
    storageBucket: 'gp-2-fe52b.firebasestorage.app',
    measurementId: 'G-5VL2D40M00',
  );
}
